// CYBER CONSTELLATION — Demo Data: 8 Synthetic Investigation Cases
// ALL DATA IS SYNTHETIC — FOR DEMONSTRATION PURPOSES ONLY
// SIH26106 Grand Finale Demo Mode

window.DEMO_CASES = [
  {
    id: 'CX-1024',
    type: 'PHISHING',
    severity: 'critical',
    riskScore: 94,
    confidence: 94,
    status: 'INVESTIGATING',
    assignedTo: 'Analyst Priya S.',
    createdAt: '2026-09-06T09:42:11Z',
    lastActivity: '2026-09-06T14:01:33Z',
    subject: 'URGENT: SBI NetBanking — Verify Your Account Immediately',
    from: { name: 'SBI Customer Care', email: 'care@sbi-secure-netbanking.com', domain: 'sbi-secure-netbanking.com' },
    to: 'victim.user@nationalgov.in',
    replyTo: { email: 'harvest@malicious-collect.ru', domain: 'malicious-collect.ru' },
    returnPath: { email: 'bounce@sbi-secure-netbanking.com', domain: 'sbi-secure-netbanking.com' },
    messageId: '<20260906.9f3a1b2@mail.sbi-secure-netbanking.com>',
    auth: { spf: 'FAIL', dkim: 'FAIL', dmarc: 'FAIL' },
    domainAge: 4,
    isHomoglyph: false,
    isLookalike: true,
    lookalikeTarget: 'sbi.co.in',
    lookalikeMethod: 'Subdomain Insertion + Brand Keyword',
    suspiciousUrls: ['https://sbi-secure-netbanking.com/verify?token=a1b2c3', 'http://45.142.122.18/harvest/credentials.php'],
    relayHops: [
      { hop: 1, ip: '45.142.122.18',  country: 'Netherlands', city: 'Rotterdam',  isp: 'Flyservers Hosting BV (AS210558)', lat: 51.9244, lng: 4.4777,   isTor: false, isVpn: false, abuseScore: 65, timestamp: '09:41:58' },
      { hop: 2, ip: '194.26.29.112',  country: 'Netherlands', city: 'Amsterdam',  isp: 'M247 Ltd Cloud Hosting (AS9009)',  lat: 52.3676, lng: 4.9041,   isTor: false, isVpn: true,  abuseScore: 78, timestamp: '09:42:03' },
      { hop: 3, ip: '104.21.4.12',    country: 'United States',city: 'San Francisco', isp: 'Cloudflare Inc (AS13335)', lat: 37.7749, lng: -122.4194, isTor: false, isVpn: false, abuseScore: 5,  timestamp: '09:42:07' },
    ],
    aiFeatures: [
      'Credential harvesting language detected',
      'Lookalike domain impersonation (SBI)',
      'Reply-To domain mismatch (Russia)',
      'SPF / DKIM / DMARC all failed',
      'Display name spoofing — SBI impersonation',
      'Urgent action trigger language',
      'Newly registered domain (4 days)',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: 'CAM-091',
    scoreBreakdown: [
      { label: 'NLP Threat Signals',       score: 22 },
      { label: 'Header Anomalies',          score: 17 },
      { label: 'Authentication Failures',   score: 16 },
      { label: 'URL Risk',                  score: 12 },
      { label: 'Domain Risk',               score: 10 },
      { label: 'Infrastructure Risk',       score: 9  },
      { label: 'Campaign Correlation',      score: 8  },
    ],
    story: `At 09:41 UTC, the email entered the national mail infrastructure via a Netherlands-based hosting server (AS210558) with an abuse score of 65/100.\n\nThe visible sender claimed to represent SBI Customer Care but the sending domain — sbi-secure-netbanking.com — is a lookalike domain registered only 4 days prior, designed to visually impersonate sbi.co.in through subdomain insertion.\n\nHeader analysis revealed a Reply-To redirect to a Russian-hosted email address, routing all victim replies to attacker-controlled infrastructure. SPF, DKIM, and DMARC all failed — the sending server is not authorized by the legitimate SBI domain.\n\nThe embedded URL directs to a credential harvesting page on the same infrastructure. NLP analysis detected high-urgency language consistent with phishing social engineering.\n\nThis email is CONFIRMED PHISHING with 94% confidence. Immediate quarantine and incident response recommended. Campaign correlation links this to CAM-091 — an ongoing SBI-themed phishing campaign targeting government email accounts.`,
    dangerReasons: [
      { title: 'Lookalike Domain Attack', detail: 'sbi-secure-netbanking.com registered 4 days ago. Designed to visually impersonate sbi.co.in.' },
      { title: 'Authentication Triple Failure', detail: 'SPF, DKIM, and DMARC all failed. The sender is not authorized by SBI.' },
      { title: 'Reply-To Hijacking', detail: 'Replies are silently redirected to malicious-collect.ru (Russia).' },
      { title: 'Credential Harvesting URL', detail: 'Embedded link leads to a fake login page capturing banking credentials.' },
      { title: 'Suspicious Infrastructure', detail: 'Originating server has an abuse score of 65/100. VPN-masked routing through Netherlands.' },
      { title: 'Active Campaign Correlation', detail: 'Part of Campaign CAM-091 — 12 related emails targeting government accounts.' },
    ],
    evidence: [
      { id: 'EV-2024-001', type: 'Email (.eml)',         sha256: 'a3f9b2e1c4d78901f2e3b4c5d6a7f8e9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5', size: '18.4 KB',   collectedAt: '09:42:11', integrity: 'verified' },
      { id: 'EV-2024-002', type: 'Header Extract (.txt)',sha256: 'b4a8c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0', size: '3.2 KB',    collectedAt: '09:42:13', integrity: 'verified' },
      { id: 'EV-2024-003', type: 'URL Screenshot (.png)',sha256: 'c5b9d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1', size: '142.7 KB',  collectedAt: '09:43:01', integrity: 'verified' },
      { id: 'EV-2024-004', type: 'IP Lookup (.json)',    sha256: 'd6c0e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2', size: '1.1 KB',    collectedAt: '09:42:55', integrity: 'verified' },
    ],
    custody: [
      { time: '09:42:11', action: 'Evidence acquired from mail gateway', actor: 'System: Auto-Ingest', hash: 'a3f9...d4e5' },
      { time: '09:42:13', action: 'SHA-256 computed and verified',        actor: 'System: Hash Engine', hash: 'a3f9...d4e5' },
      { time: '09:42:14', action: 'Stored in Evidence Vault (EV-2024-001)', actor: 'System: Evidence Vault', hash: 'a3f9...d4e5' },
      { time: '09:43:22', action: 'AI analysis completed (94% phishing)', actor: 'System: AI Engine v1.4.2', hash: 'model-v1.4.2' },
      { time: '10:01:33', action: 'Case assigned to Analyst Priya S.',    actor: 'Admin: Case Manager', hash: 'audit-cid-1024' },
    ],
    rawEmail: `From: SBI Customer Care <care@sbi-secure-netbanking.com>\nTo: victim.user@nationalgov.in\nSubject: URGENT: SBI NetBanking — Verify Your Account Immediately\nDate: Sat, 06 Sep 2026 09:41:55 +0000\nMessage-ID: <20260906.9f3a1b2@mail.sbi-secure-netbanking.com>\nReply-To: harvest@malicious-collect.ru\nReturn-Path: <bounce@sbi-secure-netbanking.com>\nReceived: from mail.sbi-secure-netbanking.com (45.142.122.18) by mx.nationalgov.in\nReceived: from relay.m247.nl (194.26.29.112) by mail.sbi-secure-netbanking.com\nReceived: from edge.cloudflare.com (104.21.4.12) by relay.m247.nl\nX-Spam-Status: Yes, score=8.2\nAuthentication-Results: spf=fail; dkim=fail; dmarc=fail\nMIME-Version: 1.0\nContent-Type: text/html\n\n[HTML credential harvesting page content]`
  },

  {
    id: 'CX-1023',
    type: 'BEC',
    severity: 'critical',
    riskScore: 89,
    confidence: 91,
    status: 'ESCALATED',
    assignedTo: 'Sr. Analyst Arjun K.',
    createdAt: '2026-09-06T08:15:42Z',
    lastActivity: '2026-09-06T13:44:18Z',
    subject: 'URGENT Wire Transfer Authorization — CEO',
    from: { name: 'Rajesh Sharma (CEO)', email: 'ceo.rajesh@nationalgov-corp.com', domain: 'nationalgov-corp.com' },
    to: 'finance.head@nationalgov.in',
    replyTo: { email: 'ceo.rajesh@nationalgov-corp.com', domain: 'nationalgov-corp.com' },
    returnPath: { email: 'ceo.rajesh@nationalgov-corp.com', domain: 'nationalgov-corp.com' },
    messageId: '<bec20260906.ceo@nationalgov-corp.com>',
    auth: { spf: 'FAIL', dkim: 'FAIL', dmarc: 'FAIL' },
    domainAge: 7,
    isHomoglyph: false,
    isLookalike: true,
    lookalikeTarget: 'nationalgov.in',
    lookalikeMethod: 'Domain Suffix Swap + Executive Name',
    suspiciousUrls: [],
    relayHops: [
      { hop: 1, ip: '195.133.40.102', country: 'Ukraine',      city: 'Kyiv',       isp: 'FastVPS / Bulletproof (AS44050)', lat: 50.4501, lng: 30.5234, isTor: false, isVpn: true,  abuseScore: 91, timestamp: '08:15:31' },
      { hop: 2, ip: '46.161.27.151',  country: 'Russia',       city: 'St. Petersburg', isp: 'Selectel LLC (AS49505)',    lat: 59.9343, lng: 30.3351, isTor: false, isVpn: true,  abuseScore: 88, timestamp: '08:15:37' },
    ],
    aiFeatures: [
      'BEC wire transfer coercion language',
      'C-Suite impersonation (CEO)',
      'Executive urgency pressure tactic',
      'Lookalike corporate domain (7 days old)',
      'Bulletproof hosting origination',
      'High abuse score infrastructure (91%)',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: 'CAM-087',
    scoreBreakdown: [
      { label: 'BEC Coercion Language',     score: 24 },
      { label: 'Infrastructure Risk',        score: 20 },
      { label: 'Domain Impersonation',       score: 18 },
      { label: 'Authentication Failures',    score: 15 },
      { label: 'Header Anomalies',           score: 8  },
      { label: 'Geo Anomaly',                score: 4  },
    ],
    story: `At 08:15 UTC, a Business Email Compromise (BEC) attempt was detected targeting the finance department.\n\nThe email impersonated the CEO using a domain registered 7 days ago — nationalgov-corp.com — designed to closely resemble the legitimate nationalgov.in domain through suffix manipulation.\n\nThe email originated from bulletproof hosting infrastructure in Ukraine (AS44050, abuse score 91/100) and routed through Russian infrastructure.\n\nContent analysis identified executive wire transfer coercion language consistent with BEC attacks. No malicious URLs were embedded — this is a pure social engineering attack relying on impersonation and urgency.\n\nConfidence: 91% BEC. Immediate escalation and financial verification required.`,
    dangerReasons: [
      { title: 'Executive Impersonation (CEO)', detail: 'Attacker impersonated CEO Rajesh Sharma using a 7-day-old lookalike domain.' },
      { title: 'Wire Transfer Coercion', detail: 'BEC-pattern language demanding urgent, unauthorized financial transfer.' },
      { title: 'Bulletproof Hosting (Abuse 91%)', detail: 'Infrastructure hosted on known bulletproof VPS with abuse score 91/100.' },
      { title: 'Authentication Triple Failure', detail: 'SPF, DKIM, DMARC all failed — domain not authorized.' },
    ],
    evidence: [
      { id: 'EV-2023-001', type: 'Email (.eml)',   sha256: 'e7d1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1', size: '12.1 KB', collectedAt: '08:15:42', integrity: 'verified' },
      { id: 'EV-2023-002', type: 'WHOIS Report',   sha256: 'f8e2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2', size: '2.8 KB',  collectedAt: '08:16:01', integrity: 'verified' },
    ],
    custody: [
      { time: '08:15:42', action: 'Email flagged by BEC detection engine', actor: 'System: BEC Module', hash: 'e7d1...d0e1' },
      { time: '08:16:01', action: 'SHA-256 computed and stored',          actor: 'System: Hash Engine', hash: 'e7d1...d0e1' },
      { time: '08:44:18', action: 'Case escalated to Sr. Analyst',        actor: 'System: Auto-Escalation', hash: 'audit-cid-1023' },
    ],
    rawEmail: `From: Rajesh Sharma (CEO) <ceo.rajesh@nationalgov-corp.com>\nTo: finance.head@nationalgov.in\nSubject: URGENT Wire Transfer Authorization — CEO\nDate: Sat, 06 Sep 2026 08:15:22 +0000\nMessage-ID: <bec20260906.ceo@nationalgov-corp.com>\nReceived: from mail.nationalgov-corp.com (195.133.40.102) by mx.nationalgov.in\nReceived: from relay.selectel.ru (46.161.27.151) by mail.nationalgov-corp.com\nAuthentication-Results: spf=fail; dkim=fail; dmarc=fail\n\nPlease initiate an immediate wire transfer of INR 14,00,000 to the following account for a critical government project. Do not discuss with anyone — classified matter. Confirm immediately. - CEO Rajesh`
  },

  {
    id: 'CX-1022',
    type: 'INVOICE FRAUD',
    severity: 'high',
    riskScore: 76,
    confidence: 78,
    status: 'REVIEW',
    assignedTo: 'Analyst Meera T.',
    createdAt: '2026-09-05T14:22:07Z',
    lastActivity: '2026-09-06T11:30:00Z',
    subject: 'Invoice #INV-2026-8821 — Payment Due Notice',
    from: { name: 'Accounts Dept — TechVendor Solutions', email: 'accounts@techvendor-solutions.net', domain: 'techvendor-solutions.net' },
    to: 'payments@nationalgov.in',
    replyTo: { email: 'accounts@techvendor-solutions.net', domain: 'techvendor-solutions.net' },
    returnPath: { email: 'accounts@techvendor-solutions.net', domain: 'techvendor-solutions.net' },
    messageId: '<inv20260905.acc@techvendor-solutions.net>',
    auth: { spf: 'SOFTFAIL', dkim: 'PASS', dmarc: 'FAIL' },
    domainAge: 21,
    isHomoglyph: false,
    isLookalike: true,
    lookalikeTarget: 'techvendor.co.in',
    lookalikeMethod: 'Domain Extension Substitution (.net vs .co.in)',
    suspiciousUrls: ['https://techvendor-solutions.net/invoice/pay?id=8821'],
    relayHops: [
      { hop: 1, ip: '95.214.25.1',    country: 'Romania',  city: 'Bucharest',  isp: 'M247 Ltd (AS9009)',   lat: 44.4268, lng: 26.1025, isTor: false, isVpn: true,  abuseScore: 72, timestamp: '14:22:01' },
      { hop: 2, ip: '178.32.105.201', country: 'France',   city: 'Paris',      isp: 'OVH SAS (AS16276)',   lat: 48.8566, lng: 2.3522,  isTor: false, isVpn: false, abuseScore: 30, timestamp: '14:22:05' },
    ],
    aiFeatures: [
      'Invoice fraud financial diversion pattern',
      'Legitimate-vendor domain lookalike (21 days old)',
      'SPF Softfail — partial authorization failure',
      'DMARC policy violation',
      'VPN-masked origination (Romania)',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: 'CAM-088',
    scoreBreakdown: [
      { label: 'Financial Diversion Language', score: 22 },
      { label: 'Domain Impersonation',         score: 18 },
      { label: 'Infrastructure Risk',           score: 14 },
      { label: 'Authentication Partial Fail',   score: 12 },
      { label: 'URL Risk',                      score: 10 },
    ],
    story: `On September 5th at 14:22 UTC, a fake invoice email was detected targeting the payments department.\n\nThe sender impersonated TechVendor Solutions using a lookalike domain registered 21 days ago, substituting the legitimate .co.in extension with .net.\n\nThe SPF record returned SOFTFAIL and DMARC policy was violated. Originating infrastructure is a VPN-masked server in Romania with an abuse score of 72/100.\n\nThe embedded payment link directs to attacker-controlled infrastructure. Invoice fraud pattern language detected with 78% confidence.\n\nCase is under review. Verification of the legitimate vendor relationship recommended before any payment action.`,
    dangerReasons: [
      { title: 'Fake Vendor Impersonation',  detail: 'techvendor-solutions.net is a 21-day-old lookalike of the legitimate techvendor.co.in.' },
      { title: 'Fraudulent Payment Link',    detail: 'Invoice payment URL routes to attacker-controlled infrastructure.' },
      { title: 'SPF Softfail + DMARC Fail', detail: 'Authentication partially failed — sender not fully authorized.' },
      { title: 'VPN-masked Infrastructure', detail: 'Origination masked through Romanian VPN (abuse score 72%).' },
    ],
    evidence: [
      { id: 'EV-1022-001', type: 'Email (.eml)',  sha256: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2', size: '24.8 KB', collectedAt: '14:22:07', integrity: 'verified' },
      { id: 'EV-1022-002', type: 'Invoice PDF',   sha256: 'b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3', size: '89.3 KB', collectedAt: '14:22:09', integrity: 'verified' },
    ],
    custody: [
      { time: '14:22:07', action: 'Email flagged by fraud detection module', actor: 'System: Fraud Engine', hash: 'a1b2...a1b2' },
      { time: '14:22:09', action: 'Attachment extracted and hashed',         actor: 'System: Attachment Engine', hash: 'b2c3...b2c3' },
    ],
    rawEmail: `From: Accounts Dept — TechVendor Solutions <accounts@techvendor-solutions.net>\nTo: payments@nationalgov.in\nSubject: Invoice #INV-2026-8821 — Payment Due Notice\nAuthentication-Results: spf=softfail; dkim=pass; dmarc=fail\nReceived: from mail.techvendor-solutions.net (95.214.25.1)\nReceived: from proxy.ovh.fr (178.32.105.201)`
  },

  {
    id: 'CX-1021',
    type: 'CREDENTIAL HARVEST',
    severity: 'critical',
    riskScore: 91,
    confidence: 92,
    status: 'INVESTIGATING',
    assignedTo: 'Analyst Karan B.',
    createdAt: '2026-09-06T07:03:19Z',
    lastActivity: '2026-09-06T12:15:44Z',
    subject: 'Action Required: Your Government Portal Access Will Expire in 24 Hours',
    from: { name: 'NIC Portal Admin', email: 'admin@gov-nic-portal-secure.com', domain: 'gov-nic-portal-secure.com' },
    to: 'employee@gov.in',
    replyTo: { email: 'admin@gov-nic-portal-secure.com', domain: 'gov-nic-portal-secure.com' },
    returnPath: { email: 'admin@gov-nic-portal-secure.com', domain: 'gov-nic-portal-secure.com' },
    messageId: '<nic20260906.admin@gov-nic-portal-secure.com>',
    auth: { spf: 'FAIL', dkim: 'FAIL', dmarc: 'FAIL' },
    domainAge: 2,
    isHomoglyph: false,
    isLookalike: true,
    lookalikeTarget: 'nic.in',
    lookalikeMethod: 'Brand Keyword Injection + Subdomain Abuse',
    suspiciousUrls: ['https://gov-nic-portal-secure.com/login?redirect=portal.gov.in', 'https://gov-nic-portal-secure.com/session-expire'],
    relayHops: [
      { hop: 1, ip: '185.220.101.5',  country: 'Russia',       city: 'Moscow',      isp: 'Tor Exit Node / Bulletproof VPS (AS49981)', lat: 55.7558, lng: 37.6173, isTor: true,  isVpn: true,  abuseScore: 98, timestamp: '07:03:08' },
      { hop: 2, ip: '185.156.73.44',  country: 'Switzerland',  city: 'Zurich',      isp: 'ProtonVPN AG Exit Pool (AS62513)',           lat: 47.3769, lng: 8.5417,  isTor: false, isVpn: true,  abuseScore: 82, timestamp: '07:03:13' },
      { hop: 3, ip: '198.54.117.197', country: 'United States',city: 'Ashburn',     isp: 'NameCheap Inc (AS22612)',                    lat: 39.0438, lng: -77.4874,isTor: false, isVpn: false, abuseScore: 40, timestamp: '07:03:17' },
    ],
    aiFeatures: [
      'Government portal credential harvesting',
      'Tor exit node origination (abuse 98%)',
      'NIC.IN brand impersonation',
      'Domain age: 2 days',
      'Triple authentication failure',
      'Deceptive redirect URL to legitimate-looking portal',
      'Account expiry urgency tactic',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: 'CAM-091',
    scoreBreakdown: [
      { label: 'Credential Harvesting Language', score: 24 },
      { label: 'Infrastructure Risk (Tor)',       score: 22 },
      { label: 'Authentication Failures',         score: 16 },
      { label: 'Domain Risk (2 days old)',         score: 14 },
      { label: 'URL Risk',                        score: 12 },
      { label: 'Campaign Correlation',            score: 3  },
    ],
    story: `At 07:03 UTC, a highly sophisticated government portal credential harvesting email was detected.\n\nThe originating server is a known Tor exit node in Moscow with an abuse score of 98/100 — the highest possible risk infrastructure. The email then routed through a ProtonVPN exit in Switzerland before reaching the US-based mail relay.\n\nThe sending domain gov-nic-portal-secure.com was registered only 2 days ago, impersonating the National Informatics Centre (NIC). The fraudulent portal URL uses a deceptive redirect parameter (redirect=portal.gov.in) to appear legitimate.\n\nTriple authentication failure (SPF/DKIM/DMARC). This is a STATE-LEVEL capability phishing attack targeting government employee credentials. Immediate quarantine, credential reset, and CERT-In notification recommended.`,
    dangerReasons: [
      { title: 'Tor Exit Node Origination (98% Abuse)', detail: 'Email originated from confirmed Tor exit node — highest risk infrastructure.' },
      { title: 'Government Portal Impersonation',       detail: 'NIC portal brand impersonated on a 2-day-old domain.' },
      { title: 'Deceptive Redirect URL',                detail: 'Login URL uses redirect=portal.gov.in to appear legitimate to victims.' },
      { title: 'Triple Authentication Failure',         detail: 'SPF, DKIM, DMARC all failed — confirmed unauthorized sender.' },
      { title: 'Multi-Country Infrastructure Chain',    detail: 'Russia → Switzerland → USA routing chain to obscure origin.' },
    ],
    evidence: [
      { id: 'EV-1021-001', type: 'Email (.eml)',      sha256: 'c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4', size: '19.2 KB', collectedAt: '07:03:19', integrity: 'verified' },
      { id: 'EV-1021-002', type: 'URL Screenshot',    sha256: 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5', size: '198.4 KB',collectedAt: '07:04:11', integrity: 'verified' },
      { id: 'EV-1021-003', type: 'Tor IP Evidence',   sha256: 'e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6', size: '0.9 KB',  collectedAt: '07:03:45', integrity: 'verified' },
    ],
    custody: [
      { time: '07:03:19', action: 'Email acquired — Tor node flag triggered', actor: 'System: Geo Engine',  hash: 'c3d4...c3d4' },
      { time: '07:03:45', action: 'Tor exit node confirmed via threat DB',    actor: 'System: TI Engine',   hash: 'e5f6...e5f6' },
      { time: '07:04:11', action: 'URL screenshotted and archived',           actor: 'System: URL Engine',  hash: 'd4e5...d4e5' },
    ],
    rawEmail: `From: NIC Portal Admin <admin@gov-nic-portal-secure.com>\nTo: employee@gov.in\nSubject: Action Required: Your Government Portal Access Will Expire in 24 Hours\nAuthentication-Results: spf=fail; dkim=fail; dmarc=fail\nReceived: from mail.gov-nic-portal-secure.com (198.54.117.197)\nReceived: from vpn-exit.protonvpn.ch (185.156.73.44)\nReceived: from tor-exit.anonymize.ru (185.220.101.5)`
  },

  {
    id: 'CX-1020',
    type: 'SPOOFING',
    severity: 'high',
    riskScore: 71,
    confidence: 82,
    status: 'REVIEW',
    assignedTo: 'Analyst Divya N.',
    createdAt: '2026-09-05T16:44:31Z',
    lastActivity: '2026-09-06T09:22:17Z',
    subject: 'Important Policy Update from Ministry of Finance',
    from: { name: 'Ministry of Finance — India', email: 'circular@finmin.india-policy.org', domain: 'finmin.india-policy.org' },
    to: 'all-staff@gov.in',
    replyTo: { email: 'circular@finmin.india-policy.org', domain: 'finmin.india-policy.org' },
    returnPath: { email: 'circular@finmin.india-policy.org', domain: 'finmin.india-policy.org' },
    messageId: '<mof20260905.circular@finmin.india-policy.org>',
    auth: { spf: 'FAIL', dkim: 'FAIL', dmarc: 'FAIL' },
    domainAge: 14,
    isHomoglyph: false,
    isLookalike: true,
    lookalikeTarget: 'finmin.gov.in',
    lookalikeMethod: 'Government TLD Substitution',
    suspiciousUrls: ['https://finmin.india-policy.org/circular/policy-2026.pdf'],
    relayHops: [
      { hop: 1, ip: '103.149.28.78', country: 'China',       city: 'Beijing',   isp: 'Alibaba Cloud (AS37963)', lat: 39.9042, lng: 116.4074, isTor: false, isVpn: false, abuseScore: 55, timestamp: '16:44:22' },
      { hop: 2, ip: '91.108.56.122', country: 'Germany',     city: 'Frankfurt', isp: 'DE Cloud Provider (AS62014)', lat: 50.1109, lng: 8.6821, isTor: false, isVpn: false, abuseScore: 20, timestamp: '16:44:27' },
    ],
    aiFeatures: [
      'Government ministry impersonation',
      'TLD substitution (.org vs .gov.in)',
      'Circular/policy document social engineering',
      'Triple authentication failure',
      'China-based origination',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: 'CAM-089',
    scoreBreakdown: [
      { label: 'Government Impersonation', score: 22 },
      { label: 'Authentication Failures', score: 18 },
      { label: 'Domain Risk',             score: 14 },
      { label: 'Infrastructure Risk',     score: 10 },
      { label: 'URL Risk',                score: 7  },
    ],
    story: `On September 5th at 16:44 UTC, an email spoofing the Ministry of Finance was detected.\n\nThe sender used finmin.india-policy.org — registered 14 days prior — to impersonate the legitimate finmin.gov.in domain through TLD substitution.\n\nThe email originated from Alibaba Cloud infrastructure in China and routed through German relay infrastructure. SPF, DKIM, and DMARC all failed.\n\nA PDF link purporting to be a policy circular was embedded. Content analysis detected government circular social engineering language. 82% confidence spoofing/phishing assessment.`,
    dangerReasons: [
      { title: 'Ministry of Finance Impersonation', detail: 'finmin.india-policy.org impersonates finmin.gov.in using .org TLD.' },
      { title: 'China-Based Infrastructure',       detail: 'Origination from Alibaba Cloud China (abuse score 55%).' },
      { title: 'Fake Government Circular PDF',     detail: 'PDF link likely contains malware or credential harvesting page.' },
      { title: 'Mass Targeting',                   detail: 'Sent to all-staff mailing list — large-scale spear-phishing attempt.' },
    ],
    evidence: [
      { id: 'EV-1020-001', type: 'Email (.eml)', sha256: 'f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7', size: '16.4 KB', collectedAt: '16:44:31', integrity: 'verified' },
    ],
    custody: [
      { time: '16:44:31', action: 'Email flagged — government impersonation', actor: 'System: Domain Engine', hash: 'f6a7...f6a7' },
    ],
    rawEmail: `From: Ministry of Finance — India <circular@finmin.india-policy.org>\nTo: all-staff@gov.in\nSubject: Important Policy Update from Ministry of Finance\nAuthentication-Results: spf=fail; dkim=fail; dmarc=fail\nReceived: from mail.finmin.india-policy.org (103.149.28.78)`
  },

  {
    id: 'CX-1019',
    type: 'MULTI-HOP RELAY',
    severity: 'high',
    riskScore: 83,
    confidence: 85,
    status: 'INVESTIGATING',
    assignedTo: 'Analyst Rohit M.',
    createdAt: '2026-09-05T11:18:52Z',
    lastActivity: '2026-09-06T10:08:29Z',
    subject: 'Security Alert: Unauthorized Login Detected — Immediate Action Required',
    from: { name: 'CERT-In Security Team', email: 'alert@cert-in-security.org', domain: 'cert-in-security.org' },
    to: 'sysadmin@gov.in',
    replyTo: { email: 'response@cert-in-response.net', domain: 'cert-in-response.net' },
    returnPath: { email: 'alert@cert-in-security.org', domain: 'cert-in-security.org' },
    messageId: '<certin20260905.alert@cert-in-security.org>',
    auth: { spf: 'FAIL', dkim: 'FAIL', dmarc: 'FAIL' },
    domainAge: 9,
    isHomoglyph: false,
    isLookalike: true,
    lookalikeTarget: 'cert-in.org.in',
    lookalikeMethod: 'TLD Simplification + Brand Name',
    suspiciousUrls: ['https://cert-in-security.org/login-verify?session=abc123def'],
    relayHops: [
      { hop: 1, ip: '195.133.40.102', country: 'Ukraine',       city: 'Kyiv',           isp: 'FastVPS Bulletproof (AS44050)', lat: 50.4501, lng: 30.5234, isTor: false, isVpn: true,  abuseScore: 91, timestamp: '11:18:40' },
      { hop: 2, ip: '46.161.27.151',  country: 'Russia',        city: 'St. Petersburg', isp: 'Selectel LLC (AS49505)',        lat: 59.9343, lng: 30.3351, isTor: false, isVpn: true,  abuseScore: 88, timestamp: '11:18:44' },
      { hop: 3, ip: '178.32.105.201', country: 'France',        city: 'Paris',          isp: 'OVH SAS (AS16276)',             lat: 48.8566, lng: 2.3522,  isTor: false, isVpn: false, abuseScore: 30, timestamp: '11:18:48' },
      { hop: 4, ip: '104.21.4.12',    country: 'United States', city: 'San Francisco',  isp: 'Cloudflare Inc (AS13335)',      lat: 37.7749, lng: -122.4194,isTor: false, isVpn: false, abuseScore: 5,  timestamp: '11:18:51' },
    ],
    aiFeatures: [
      'CERT-In impersonation (4-hop relay chain)',
      'Reply-To domain mismatch (cert-in-response.net)',
      'Multi-country relay obfuscation',
      'Ukraine → Russia → France → USA routing',
      'Security alert urgency language',
      'Domain age: 9 days',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: 'CAM-090',
    scoreBreakdown: [
      { label: 'Infrastructure Relay Chain',   score: 24 },
      { label: 'CERT-In Impersonation',        score: 22 },
      { label: 'Authentication Failures',      score: 15 },
      { label: 'Reply-To Mismatch',            score: 12 },
      { label: 'Domain Risk (9 days)',          score: 10 },
    ],
    story: `On September 5th, a sophisticated multi-hop relay attack impersonating CERT-In was detected.\n\nThe email traversed a 4-hop relay chain: Ukraine → Russia → France → USA, deliberately obscuring the true origin. Both originating hops (Ukraine AS44050, Russia AS49505) are known bulletproof hosting providers with abuse scores above 88%.\n\nThe sending domain cert-in-security.org (9 days old) impersonates the legitimate cert-in.org.in. Additionally, the Reply-To domain differs — replies are captured by a second attacker-controlled domain.\n\nSecurity alert language designed to urgently provoke administrator action. This is a sophisticated infrastructure attack requiring full relay chain investigation. STRAD analysis identified timing anomalies in the relay chain consistent with artificial delay injection.`,
    dangerReasons: [
      { title: '4-Hop Relay Obfuscation Chain', detail: 'Ukraine → Russia → France → USA — deliberate origin concealment.' },
      { title: 'CERT-In Authority Impersonation', detail: 'cert-in-security.org impersonates the national cybersecurity authority.' },
      { title: 'Bulletproof Infrastructure',     detail: 'Two origination hops using known bulletproof hosting (abuse 88-91%).' },
      { title: 'Reply-To Domain Hijack',         detail: 'Admin replies captured by second attacker-controlled domain.' },
    ],
    evidence: [
      { id: 'EV-1019-001', type: 'Email (.eml)',       sha256: 'a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8', size: '21.6 KB', collectedAt: '11:18:52', integrity: 'verified' },
      { id: 'EV-1019-002', type: 'Relay Analysis',     sha256: 'b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9', size: '4.8 KB',  collectedAt: '11:19:31', integrity: 'verified' },
    ],
    custody: [
      { time: '11:18:52', action: 'Multi-hop relay chain detected',         actor: 'System: STRAD Engine', hash: 'a7b8...a7b8' },
      { time: '11:19:31', action: 'Relay chain analyzed and documented',    actor: 'System: Geo Engine',   hash: 'b8c9...b8c9' },
    ],
    rawEmail: `From: CERT-In Security Team <alert@cert-in-security.org>\nTo: sysadmin@gov.in\nReply-To: response@cert-in-response.net\nAuthentication-Results: spf=fail; dkim=fail; dmarc=fail\nReceived: from edge.cloudflare.com (104.21.4.12)\nReceived: from relay.ovh.fr (178.32.105.201)\nReceived: from relay.selectel.ru (46.161.27.151)\nReceived: from mail.cert-in-security.org (195.133.40.102)`
  },

  {
    id: 'CX-1018',
    type: 'CAMPAIGN',
    severity: 'critical',
    riskScore: 87,
    confidence: 88,
    status: 'ESCALATED',
    assignedTo: 'Sr. Analyst Priya S.',
    createdAt: '2026-09-04T10:22:41Z',
    lastActivity: '2026-09-06T13:55:02Z',
    subject: 'Shared Document: FY2027 Budget Allocation — Review Required',
    from: { name: 'Google Drive Notifications', email: 'noreply@google-docs-share.com', domain: 'google-docs-share.com' },
    to: 'director@gov.in',
    replyTo: { email: 'noreply@google-docs-share.com', domain: 'google-docs-share.com' },
    returnPath: { email: 'noreply@google-docs-share.com', domain: 'google-docs-share.com' },
    messageId: '<gdocs20260904.share@google-docs-share.com>',
    auth: { spf: 'FAIL', dkim: 'FAIL', dmarc: 'FAIL' },
    domainAge: 3,
    isHomoglyph: false,
    isLookalike: true,
    lookalikeTarget: 'google.com',
    lookalikeMethod: 'Brand Service Impersonation',
    suspiciousUrls: ['https://google-docs-share.com/d/view?id=BudgetFY2027', 'https://google-docs-share.com/auth/google-login'],
    relayHops: [
      { hop: 1, ip: '185.220.101.5', country: 'Russia',      city: 'Moscow',      isp: 'Tor Exit / Bulletproof (AS49981)', lat: 55.7558, lng: 37.6173, isTor: true,  isVpn: true,  abuseScore: 98, timestamp: '10:22:29' },
      { hop: 2, ip: '45.142.122.18', country: 'Netherlands', city: 'Rotterdam',   isp: 'Flyservers Hosting BV (AS210558)',lat: 51.9244, lng: 4.4777,  isTor: false, isVpn: false, abuseScore: 65, timestamp: '10:22:35' },
      { hop: 3, ip: '209.85.216.44', country: 'United States',city: 'Mountain View', isp: 'Google LLC (AS15169)',         lat: 37.3861, lng:-122.0839,isTor: false, isVpn: false, abuseScore: 0,  timestamp: '10:22:39' },
    ],
    aiFeatures: [
      'Google Drive notification impersonation',
      '3-day-old lookalike domain',
      'Tor exit origination (98% abuse)',
      'Legitimate relay injection (Google AS15169) for deception',
      'Part of active CAM-091 campaign (12 related emails)',
      'High-value target (Director-level)',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: 'CAM-091',
    scoreBreakdown: [
      { label: 'Infrastructure Risk (Tor)',      score: 26 },
      { label: 'Brand Impersonation',            score: 22 },
      { label: 'Authentication Failures',        score: 16 },
      { label: 'Campaign Correlation',           score: 12 },
      { label: 'URL Risk',                       score: 11 },
    ],
    story: `On September 4th, a Google Drive impersonation email targeting a Director-level account was detected.\n\nThis email is confirmed as part of Campaign CAM-091 — an active credential harvesting campaign with 12 related emails targeting government officials. The campaign uses Google service impersonation to lure high-value targets.\n\nThe email originated from a confirmed Tor exit node (abuse 98%) in Moscow, then used Netherlands hosting before injecting into a legitimate Google infrastructure relay — a sophisticated technique to partially legitimize the relay chain to automated systems.\n\nThe linked document URL leads to a fake Google login credential harvesting page. High-value director targeting + campaign correlation elevates this to CRITICAL priority.`,
    dangerReasons: [
      { title: 'Active Campaign CAM-091 (12 Emails)', detail: 'Part of coordinated government-targeting campaign.' },
      { title: 'Google Service Impersonation',        detail: 'google-docs-share.com (3 days old) impersonates Google Drive notifications.' },
      { title: 'Tor + Legitimate Relay Injection',   detail: 'Sophisticated technique: Tor origin hidden by routing through Google AS.' },
      { title: 'High-Value Director Targeting',      detail: 'Specifically targeted Director-level account — spear-phishing.' },
    ],
    evidence: [
      { id: 'EV-1018-001', type: 'Email (.eml)',     sha256: 'c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0', size: '16.8 KB', collectedAt: '10:22:41', integrity: 'verified' },
    ],
    custody: [
      { time: '10:22:41', action: 'Email flagged by campaign correlation engine', actor: 'System: Campaign Engine', hash: 'c9d0...c9d0' },
    ],
    rawEmail: `From: Google Drive Notifications <noreply@google-docs-share.com>\nTo: director@gov.in\nAuthentication-Results: spf=fail; dkim=fail; dmarc=fail\nReceived: from mail.google.com (209.85.216.44)\nReceived: from relay.flyservers.nl (45.142.122.18)\nReceived: from tor-exit.anonymize.ru (185.220.101.5)`
  },

  {
    id: 'CX-1017',
    type: 'LEGITIMATE',
    severity: 'safe',
    riskScore: 8,
    confidence: 97,
    status: 'CLOSED',
    assignedTo: 'System',
    createdAt: '2026-09-06T11:30:00Z',
    lastActivity: '2026-09-06T11:30:45Z',
    subject: 'Monthly Security Newsletter — September 2026',
    from: { name: 'CERT-In Newsletter', email: 'newsletter@cert-in.org.in', domain: 'cert-in.org.in' },
    to: 'security@gov.in',
    replyTo: { email: 'newsletter@cert-in.org.in', domain: 'cert-in.org.in' },
    returnPath: { email: 'newsletter@cert-in.org.in', domain: 'cert-in.org.in' },
    messageId: '<nl20260906.sep@cert-in.org.in>',
    auth: { spf: 'PASS', dkim: 'PASS', dmarc: 'PASS' },
    domainAge: 4380,
    isHomoglyph: false,
    isLookalike: false,
    lookalikeTarget: null,
    lookalikeMethod: null,
    suspiciousUrls: [],
    relayHops: [
      { hop: 1, ip: '122.165.0.1',   country: 'India', city: 'Mumbai',    isp: 'BSNL India (AS9829)',   lat: 19.0760, lng: 72.8777, isTor: false, isVpn: false, abuseScore: 12, timestamp: '11:29:51' },
      { hop: 2, ip: '49.44.85.152',  country: 'India', city: 'New Delhi', isp: 'Airtel (AS24560)',       lat: 28.6139, lng: 77.2090, isTor: false, isVpn: false, abuseScore: 8,  timestamp: '11:29:56' },
    ],
    aiFeatures: [
      'All authentication passed (SPF/DKIM/DMARC)',
      'Legitimate CERT-In domain (12 years old)',
      'India-domestic routing',
      'Low infrastructure risk',
      'No suspicious URLs or attachments',
      'Informational newsletter content',
    ],
    aiModel: { name: 'EmailThreatClassifier', version: 'v1.4.2', dataset: 'dataset-2026-08', threshold: 0.78 },
    campaignId: null,
    scoreBreakdown: [
      { label: 'Authentication — All Passed',    score: 0 },
      { label: 'Domain Risk — Established',      score: 0 },
      { label: 'Infrastructure — Legitimate',    score: 0 },
      { label: 'Content — Informational',        score: 0 },
      { label: 'Minor: Marketing-style language', score: 8 },
    ],
    story: `At 11:30 UTC, an email from the official CERT-In newsletter service was analyzed.\n\nAll three authentication checks (SPF, DKIM, DMARC) passed. The sending domain cert-in.org.in is 12 years old and is the verified official domain of the Indian Computer Emergency Response Team.\n\nThe email routed through legitimate Indian domestic infrastructure (BSNL and Airtel) with low abuse scores (8-12/100).\n\nNo suspicious URLs, attachments, or social engineering language detected. Risk score: 8/100 (minimal — attributed to standard marketing-style newsletter formatting).\n\nCONCLUSION: LEGITIMATE EMAIL. Automatically closed.`,
    dangerReasons: [],
    evidence: [
      { id: 'EV-1017-001', type: 'Email (.eml)', sha256: 'd0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1', size: '44.2 KB', collectedAt: '11:30:00', integrity: 'verified' },
    ],
    custody: [
      { time: '11:30:00', action: 'Email received and analyzed',      actor: 'System: Full Pipeline',  hash: 'd0e1...d0e1' },
      { time: '11:30:45', action: 'Auto-closed — legitimate email',   actor: 'System: Risk Engine',    hash: 'audit-cid-1017' },
    ],
    rawEmail: `From: CERT-In Newsletter <newsletter@cert-in.org.in>\nTo: security@gov.in\nAuthentication-Results: spf=pass; dkim=pass; dmarc=pass\nReceived: from smtp.cert-in.org.in (49.44.85.152)\nReceived: from mx.bsnl.in (122.165.0.1)`
  }
];

// Demo Pulse Feed Events
window.DEMO_PULSE = [
  { time: '14:41:08', severity: 'critical', msg: 'Critical phishing email detected — CX-1024 (Score: 94/100)' },
  { time: '14:40:44', severity: 'high',     msg: 'New suspicious domain linked to Campaign CAM-091' },
  { time: '14:39:21', severity: 'medium',   msg: 'SPF failure detected — sbi-secure-netbanking.com' },
  { time: '14:38:52', severity: 'info',     msg: 'New infrastructure correlation discovered (Netherlands cluster)' },
  { time: '14:37:19', severity: 'critical', msg: 'Tor exit node origination confirmed — CX-1021' },
  { time: '14:36:08', severity: 'high',     msg: 'BEC case CX-1023 escalated to senior analyst' },
  { time: '14:35:44', severity: 'info',     msg: 'Campaign CAM-091 now has 12 correlated emails' },
  { time: '14:34:31', severity: 'medium',   msg: 'Domain age anomaly: cert-in-security.org (9 days)' },
  { time: '14:33:15', severity: 'info',     msg: 'Legitimate email CX-1017 auto-closed (Score: 8/100)' },
  { time: '14:32:07', severity: 'high',     msg: 'Multi-hop relay chain detected — 4 hops (Ukraine→Russia→France→USA)' },
];

// Demo quick stats
window.DEMO_STATS = {
  activeCases: 37,
  criticalThreats: 8,
  phishingDetected: 142,
  activeCampaigns: 12,
  suspiciousInfrastructure: 86,
  investigationsToday: 29,
  trends: {
    activeCases: { change: 12, direction: 'up' },
    criticalThreats: { change: 18, direction: 'up' },
    phishingDetected: { change: 7, direction: 'up' },
    activeCampaigns: { change: 2, direction: 'up' },
    suspiciousInfrastructure: { change: 5, direction: 'up' },
    investigationsToday: { change: 15, direction: 'up' },
  }
};
