// CYBER CONSTELLATION — Report Builder
// Forensic Report Generator — Preview + PDF/JSON Export

window.ReportBuilder = (() => {
  let currentCase = null;

  function buildReport(caseData) {
    currentCase = caseData;
    return _generateHTML(caseData);
  }

  function _generateHTML(c) {
    const now = new Date().toUTCString();
    const authRow = (protocol, status) => {
      const cls = status === 'PASS' ? 'report-safe' : (status === 'SOFTFAIL' ? '' : 'report-critical');
      return `<tr><td><strong>${protocol}</strong></td><td class="${cls}">${status}</td><td>${_authDesc(protocol, status)}</td></tr>`;
    };

    const urlRows = c.suspiciousUrls.map(u =>
      `<tr><td style="word-break:break-all;font-family:monospace;font-size:11px;">${u}</td><td class="report-critical">SUSPICIOUS</td><td>Credential harvesting / malicious infrastructure</td></tr>`
    ).join('');

    const relayRows = c.relayHops.map(h =>
      `<tr><td>${h.hop}</td><td style="font-family:monospace;">${h.ip}</td><td>${h.city}, ${h.country}</td><td>${h.isp}</td><td>${h.abuseScore}%</td><td>${h.isTor ? 'YES' : 'No'}</td></tr>`
    ).join('');

    const scoreRows = c.scoreBreakdown.map(s =>
      `<tr><td>${s.label}</td><td>+${s.score}</td></tr>`
    ).join('');

    const evidenceRows = c.evidence.map(e =>
      `<tr><td>${e.id}</td><td>${e.type}</td><td style="font-family:monospace;font-size:10px;word-break:break-all;">${e.sha256.substring(0,32)}...</td><td>${e.collectedAt}</td><td style="color:${e.integrity === 'verified' ? 'green' : 'orange'};">${e.integrity.toUpperCase()}</td></tr>`
    ).join('');

    const featuresHTML = c.aiFeatures.map(f => `<li>${f}</li>`).join('');

    return `
      <div style="font-family: 'Inter', Arial, sans-serif; font-size: 13px; color: #1a202c; max-width: 800px; margin: 0 auto;">

        <!-- HEADER -->
        <div style="background: #0a0f1e; color: white; padding: 28px 32px; border-radius: 8px 8px 0 0; margin-bottom: 0;">
          <div style="display:flex; justify-content:space-between; align-items:flex-start;">
            <div>
              <div style="font-size: 0.65rem; letter-spacing: 0.15em; text-transform: uppercase; color: #8b5cf6; margin-bottom: 4px;">CYBER CONSTELLATION // FORENSIC REPORT</div>
              <div style="font-size: 1.5rem; font-weight: 700; margin-bottom: 4px;">Case ${c.id}</div>
              <div style="font-size: 0.85rem; color: #94a3b8;">${c.subject}</div>
            </div>
            <div style="text-align: right;">
              <div style="background: ${c.severity === 'critical' ? '#ff4757' : c.severity === 'high' ? '#ff6b35' : '#2dd4bf'}; color: white; padding: 8px 16px; border-radius: 6px; font-weight: 700; font-size: 0.85rem; margin-bottom: 8px;">${c.type} — RISK ${c.riskScore}/100</div>
              <div style="font-size: 0.7rem; color: #64748b;">Generated: ${now}</div>
            </div>
          </div>
        </div>

        <div style="background: #f8fafc; padding: 28px 32px; border: 1px solid #e2e8f0; border-top: none;">

          <!-- CLASSIFICATION NOTICE -->
          <div style="background: ${c.severity === 'safe' ? '#f0fdf4' : '#fff5f5'}; border: 1px solid ${c.severity === 'safe' ? '#bbf7d0' : '#fecaca'}; border-radius: 6px; padding: 14px 18px; margin-bottom: 24px;">
            <strong style="color: ${c.severity === 'safe' ? '#059669' : '#dc2626'};">⚠ ${c.severity === 'safe' ? 'LEGITIMATE EMAIL — No Action Required' : 'THREAT CONFIRMED — Immediate Action Required'}</strong>
            <p style="margin: 4px 0 0; color: #374151; font-size: 12px;">This is a SYNTHETIC DEMO REPORT generated by CYBER CONSTELLATION for SIH26106 demonstration purposes. All data is fictional.</p>
          </div>

          <!-- EXECUTIVE SUMMARY -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">1. Executive Summary</h2>
          <table style="width:100%; border-collapse:collapse; margin-bottom:20px; font-size:12px;">
            <tr><td style="padding:5px 8px; width:180px; font-weight:600; color:#64748b;">CASE ID</td><td style="padding:5px 8px;">${c.id}</td><td style="padding:5px 8px; width:180px; font-weight:600; color:#64748b;">THREAT TYPE</td><td style="padding:5px 8px;">${c.type}</td></tr>
            <tr style="background:#f1f5f9;"><td style="padding:5px 8px; font-weight:600; color:#64748b;">RISK SCORE</td><td style="padding:5px 8px;" class="${c.riskScore >= 75 ? 'report-critical' : ''}">${c.riskScore}/100</td><td style="padding:5px 8px; font-weight:600; color:#64748b;">CONFIDENCE</td><td style="padding:5px 8px;">${c.confidence}%</td></tr>
            <tr><td style="padding:5px 8px; font-weight:600; color:#64748b;">STATUS</td><td style="padding:5px 8px;">${c.status}</td><td style="padding:5px 8px; font-weight:600; color:#64748b;">ASSIGNED TO</td><td style="padding:5px 8px;">${c.assignedTo}</td></tr>
            <tr style="background:#f1f5f9;"><td style="padding:5px 8px; font-weight:600; color:#64748b;">CAMPAIGN</td><td style="padding:5px 8px;">${c.campaignId || 'None'}</td><td style="padding:5px 8px; font-weight:600; color:#64748b;">CREATED</td><td style="padding:5px 8px;">${new Date(c.createdAt).toLocaleString()}</td></tr>
          </table>

          <!-- EMAIL METADATA -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">2. Email Metadata</h2>
          <table style="width:100%; border-collapse:collapse; margin-bottom:20px; font-size:12px;">
            <tr><td style="padding:5px 8px; width:160px; font-weight:600; background:#f8fafc;">From</td><td style="padding:5px 8px; font-family:monospace;">${c.from.name} &lt;${c.from.email}&gt;</td></tr>
            <tr><td style="padding:5px 8px; font-weight:600; background:#f8fafc;">To</td><td style="padding:5px 8px; font-family:monospace;">${c.to}</td></tr>
            <tr><td style="padding:5px 8px; font-weight:600; background:#f8fafc;">Subject</td><td style="padding:5px 8px;">${c.subject}</td></tr>
            <tr><td style="padding:5px 8px; font-weight:600; background:#f8fafc;">Message-ID</td><td style="padding:5px 8px; font-family:monospace; font-size:11px;">${c.messageId}</td></tr>
            <tr><td style="padding:5px 8px; font-weight:600; background:#f8fafc;">Reply-To</td><td style="padding:5px 8px; font-family:monospace; ${c.replyTo.domain !== c.from.domain ? 'color:#dc2626; font-weight:600;' : ''}">${c.replyTo.email} ${c.replyTo.domain !== c.from.domain ? '⚠ MISMATCH' : ''}</td></tr>
            <tr><td style="padding:5px 8px; font-weight:600; background:#f8fafc;">Domain Age</td><td style="padding:5px 8px; ${c.domainAge < 30 ? 'color:#dc2626; font-weight:600;' : ''}">${c.domainAge} days ${c.domainAge < 30 ? '(Newly registered — HIGH RISK)' : ''}</td></tr>
          </table>

          <!-- AUTHENTICATION -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">3. Authentication Analysis</h2>
          <table style="width:100%; border-collapse:collapse; margin-bottom:20px; font-size:12px; border:1px solid #e2e8f0;">
            <thead><tr style="background:#f1f5f9;"><th style="padding:6px 10px; text-align:left;">Protocol</th><th style="padding:6px 10px; text-align:left;">Result</th><th style="padding:6px 10px; text-align:left;">Significance</th></tr></thead>
            <tbody>
              ${authRow('SPF', c.auth.spf)}
              ${authRow('DKIM', c.auth.dkim)}
              ${authRow('DMARC', c.auth.dmarc)}
            </tbody>
          </table>

          <!-- AI ANALYSIS -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">4. AI Threat Classification</h2>
          <p><strong>Classification:</strong> <span class="${c.riskScore >= 75 ? 'report-critical' : 'report-safe'}">${c.type}</span> | <strong>Confidence:</strong> ${c.confidence}% | <strong>Model:</strong> ${c.aiModel.name} ${c.aiModel.version}</p>
          <p style="margin-top:8px;"><strong>Contributing Factors:</strong></p>
          <ul style="margin: 8px 0 16px 20px; color: #374151; font-size:12px;">${featuresHTML}</ul>

          <!-- RISK SCORE BREAKDOWN -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">5. Risk Score Breakdown</h2>
          <table style="width:100%; border-collapse:collapse; margin-bottom:20px; font-size:12px; border:1px solid #e2e8f0;">
            <thead><tr style="background:#f1f5f9;"><th style="padding:6px 10px; text-align:left;">Signal</th><th style="padding:6px 10px; text-align:left;">Score Contribution</th></tr></thead>
            <tbody>${scoreRows}</tbody>
            <tfoot><tr style="background:#0a0f1e; color:white;"><td style="padding:8px 10px; font-weight:700;">TOTAL RISK SCORE</td><td style="padding:8px 10px; font-weight:700;">${c.riskScore}/100</td></tr></tfoot>
          </table>

          ${c.suspiciousUrls.length > 0 ? `
          <!-- URLS -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">6. URL Analysis</h2>
          <table style="width:100%; border-collapse:collapse; margin-bottom:20px; font-size:12px; border:1px solid #e2e8f0;">
            <thead><tr style="background:#f1f5f9;"><th style="padding:6px 10px;">URL</th><th style="padding:6px 10px;">Status</th><th style="padding:6px 10px;">Assessment</th></tr></thead>
            <tbody>${urlRows}</tbody>
          </table>
          ` : ''}

          <!-- SMTP RELAY CHAIN -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">7. SMTP Relay Infrastructure</h2>
          <table style="width:100%; border-collapse:collapse; margin-bottom:20px; font-size:12px; border:1px solid #e2e8f0;">
            <thead><tr style="background:#f1f5f9;"><th style="padding:6px 10px;">Hop</th><th style="padding:6px 10px;">IP Address</th><th style="padding:6px 10px;">Location</th><th style="padding:6px 10px;">Provider</th><th style="padding:6px 10px;">Abuse%</th><th style="padding:6px 10px;">Tor</th></tr></thead>
            <tbody>${relayRows}</tbody>
          </table>
          <p style="font-size:11px; color:#64748b; font-style:italic;">⚠ Note: IP geolocation indicates probable infrastructure location, not attacker physical location. Infrastructure attribution requires additional investigation.</p>

          <!-- INVESTIGATION STORY -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">8. Investigation Narrative</h2>
          <div style="background: #f8f9ff; border-left: 3px solid #8b5cf6; padding: 16px 20px; border-radius: 4px; font-style: italic; color: #374151; font-size: 12px; line-height: 1.7; margin-bottom: 20px;">
            ${c.story.split('\n\n').map(p => `<p style="margin:0 0 10px;">${p}</p>`).join('')}
          </div>

          <!-- EVIDENCE -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">9. Evidence & Chain of Custody</h2>
          <table style="width:100%; border-collapse:collapse; margin-bottom:20px; font-size:12px; border:1px solid #e2e8f0;">
            <thead><tr style="background:#f1f5f9;"><th style="padding:6px 10px;">Evidence ID</th><th style="padding:6px 10px;">Type</th><th style="padding:6px 10px;">SHA-256 (truncated)</th><th style="padding:6px 10px;">Collected At</th><th style="padding:6px 10px;">Integrity</th></tr></thead>
            <tbody>${evidenceRows}</tbody>
          </table>

          <!-- LIMITATIONS -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">10. Limitations & Attribution Disclaimer</h2>
          <ul style="margin: 0 0 20px 20px; color: #374151; font-size: 12px; line-height: 1.8;">
            <li>Geolocation reflects probable <strong>infrastructure location</strong>, not attacker physical location.</li>
            <li>IP addresses may belong to shared hosting, VPN, or compromised systems.</li>
            <li>Threat attribution beyond infrastructure correlation requires additional legal investigation.</li>
            <li>AI classification confidence reflects pattern matching — human analyst review is required for final determination.</li>
            <li>This report does not constitute legal evidence without proper digital forensics chain of custody validation.</li>
          </ul>

          <!-- RECOMMENDATIONS -->
          <h2 style="font-size: 1rem; font-weight: 700; color: #0a0f1e; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 12px;">11. Recommendations</h2>
          ${c.severity === 'safe' ? `
          <ul style="margin: 0 0 20px 20px; color: #374151; font-size: 12px; line-height: 1.8;">
            <li>No immediate action required — email is legitimate.</li>
            <li>Continue standard monitoring.</li>
          </ul>
          ` : `
          <ul style="margin: 0 0 20px 20px; color: #374151; font-size: 12px; line-height: 1.8;">
            <li>Immediately quarantine and block the sending domain: <strong>${c.from.domain}</strong></li>
            <li>Block originating IP addresses at perimeter firewall.</li>
            <li>Notify affected users and force credential resets if credentials may have been harvested.</li>
            <li>Report to CERT-In and I4C Cyber Crime Portal (cybercrime.gov.in) within 6 hours.</li>
            <li>Preserve all evidence with SHA-256 verification for legal proceedings.</li>
            ${c.campaignId ? `<li>Investigate Campaign ${c.campaignId} for additional related emails.</li>` : ''}
          </ul>
          `}

          <!-- FOOTER -->
          <div style="border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 8px; display:flex; justify-content:space-between; font-size:11px; color:#94a3b8;">
            <span>CYBER CONSTELLATION // SIH26106 // SYNTHETIC DEMO DATA</span>
            <span>Report ID: RPT-${c.id}-${Date.now().toString(36).toUpperCase()}</span>
          </div>
        </div>
      </div>
    `;
  }

  function _authDesc(protocol, status) {
    const descs = {
      'SPF-PASS': 'Sender IP authorized by domain DNS TXT record',
      'SPF-FAIL': '⚠ Sender IP NOT authorized — unauthorized sender',
      'SPF-SOFTFAIL': '⚠ Sender IP partially unauthorized — suspicious',
      'DKIM-PASS': 'Email signature cryptographically verified',
      'DKIM-FAIL': '⚠ DKIM signature invalid or missing — email may be forged',
      'DMARC-PASS': 'DMARC policy satisfied — sender aligns with policy',
      'DMARC-FAIL': '⚠ DMARC policy violated — organization policy breached',
    };
    return descs[`${protocol}-${status}`] || status;
  }

  function exportJSON(caseData) {
    const report = {
      reportMeta: {
        reportId: `RPT-${caseData.id}-${Date.now().toString(36).toUpperCase()}`,
        generatedAt: new Date().toISOString(),
        platform: 'CYBER CONSTELLATION',
        version: '3.0.0',
        note: 'SYNTHETIC DEMO DATA — SIH26106'
      },
      caseData,
      reportSections: [
        'executive_summary', 'email_metadata', 'authentication', 'ai_analysis',
        'risk_score_breakdown', 'url_analysis', 'smtp_relay', 'investigation_narrative',
        'evidence', 'chain_of_custody', 'limitations', 'recommendations'
      ]
    };

    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CYBER-CONSTELLATION-${caseData.id}-Forensic-Report.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function exportPDF() {
    window.print();
  }

  return { buildReport, exportJSON, exportPDF };
})();
